<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>7ace720e-efca-4f1f-8db6-04370a6f195f</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>

    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.12" />

    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.19" />

    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.12">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>

    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.12" />

    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.12">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="9.0.6" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Properties\" />
  </ItemGroup>

<Target Name="PublishAngular" AfterTargets="ComputeFilesToPublish">
  <Exec
    WorkingDirectory="$(MSBuildProjectDirectory)\client"
    Command="npm ci" />

  <Exec
    WorkingDirectory="$(MSBuildProjectDirectory)\client"
    Command="npm run build" />

  <ItemGroup>
    <AngularFiles Include="$(MSBuildProjectDirectory)\client\dist\client\browser\**\*" />

    <ResolvedFileToPublish
      Include="@(AngularFiles->'%(FullPath)')"
      Exclude="@(ResolvedFileToPublish)">

      <RelativePath>wwwroot\%(RecursiveDir)%(Filename)%(Extension)</RelativePath>

      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </ResolvedFileToPublish>
  </ItemGroup>
</Target>

</Project>
